"""Native Windows front end for FACTS Projection Studio.

The UI is bundled into a PyInstaller executable, so it opens before WSL, Git,
or the FACTS runtime is installed. Scientific execution remains in the tested
Ubuntu/WSL + Docker environment.
"""
from __future__ import annotations

import os
import json
import re
import shlex
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Callable

from PySide6.QtCore import QItemSelectionModel, QSettings, QThread, QTimer, QUrl, Qt, Signal
from PySide6.QtGui import QFont
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (
    QApplication, QCheckBox, QComboBox, QDialog, QDialogButtonBox, QFileDialog,
    QFormLayout, QGridLayout, QGroupBox, QHBoxLayout, QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMessageBox, QProgressBar, QPushButton, QScrollArea, QSpinBox, QSplitter,
    QTabWidget, QTableWidget, QTableWidgetItem, QTextEdit, QVBoxLayout, QWidget,
)


SCENARIOS = ("ssp119", "ssp126", "ssp245", "ssp370", "ssp585")
WORKFLOWS = ("wf1e", "wf1f", "wf2e", "wf2f", "wf3e", "wf3f", "wf4")
MODULES = (
    ("GrIS1f", "FittedISMIP", "GrIS", ("wf1f", "wf2f", "wf3f"), (), ""),
    ("deconto21", "deconto21", "AIS", ("wf3e", "wf3f"), (), ""),
    ("bamber19", "bamber19", "icesheets", ("wf4",), (), ""),
    ("emuAIS", "emulandice", "AIS", ("wf1e",), (("pyear_end", "2100"),), ""),
    ("emuGrIS", "emulandice", "GrIS", ("wf1e", "wf2e", "wf3e"), (("pyear_end", "2100"),), ""),
    ("emuglaciers", "emulandice", "glaciers", ("wf1e", "wf2e", "wf3e"), (("pyear_end", "2100"),), ""),
    ("larmip", "larmip", "AIS", ("wf2e", "wf2f"), (), ""),
    ("ar5glaciers", "ipccar5", "glaciers", ("wf1f", "wf2f", "wf3f", "wf4"), (("gmip", "2"),), ""),
    ("ar5AIS", "ipccar5", "icesheets", ("wf1f",), (), "ais"),
    ("ocean", "tlm", "sterodynamics", WORKFLOWS, (), ""),
    ("k14vlm", "kopp14", "verticallandmotion", WORKFLOWS, (), "vlm"),
    ("lws", "ssp", "landwaterstorage", WORKFLOWS, (), "lws"),
)


def package_root() -> Path:
    if getattr(sys, "frozen", False):
        executable_dir = Path(sys.executable).resolve().parent
        backend_dir = executable_dir / "_FACTS_backend"
        return backend_dir if backend_dir.is_dir() else executable_dir
    return Path(__file__).resolve().parent.parent


def run_capture(command: list[str], timeout: int = 30) -> tuple[int, str]:
    try:
        result = subprocess.run(command, capture_output=True, text=True,
                                encoding="utf-8", errors="replace", timeout=timeout)
        return result.returncode, (result.stdout + result.stderr).replace("\x00", "").strip()
    except (OSError, subprocess.SubprocessError) as exc:
        return 127, str(exc)


def ubuntu_available() -> bool:
    code, output = run_capture(["wsl.exe", "--list", "--quiet"], 20)
    return code == 0 and any(line.strip().lower() == "ubuntu"
                             for line in output.splitlines())


def wsl_home() -> str:
    code, output = run_capture(
        ["wsl.exe", "-d", "Ubuntu", "--", "bash", "-lc", "printf %s \"$HOME\""], 20)
    if code != 0 or not output.startswith("/"):
        raise RuntimeError("Could not determine the Ubuntu home directory: " + output)
    return output.splitlines()[0].strip()


def wsl_path(path: Path) -> str:
    code, output = run_capture(
        ["wsl.exe", "-d", "Ubuntu", "--", "wslpath", "-a", "-u", str(path)], 20)
    if code != 0 or not output:
        raise RuntimeError("Could not translate Windows path for WSL: " + str(path))
    return output.splitlines()[0].strip()


def docker_ready() -> tuple[bool, str]:
    code, output = run_capture(["docker.exe", "info"], 25)
    if code == 0:
        vcode, version = run_capture(
            ["docker.exe", "version", "--format", "{{.Server.Version}}"], 15)
        return True, "Engine " + (version if vcode == 0 else "running")
    return False, output.splitlines()[-1] if output else "Docker Desktop is not running"


def build_config(scenario: str, local: bool, workflows: list[str], use_vlm: bool,
                 use_esl: bool, esl_years: str, nsamps: int, baseyear: int,
                 pstart: int, pend: int, pstep: int) -> str:
    lines: list[str] = []
    add = lines.append
    lws_scenario = {
        "ssp119": "ssp1", "ssp126": "ssp1", "ssp245": "ssp2",
        "ssp370": "ssp3", "ssp585": "ssp5",
    }[scenario]
    add(f"# Generated by FACTS Projection Studio: {'LOCAL' if local else 'GLOBAL'} run")
    add(f"# {datetime.now():%Y-%m-%d %H:%M:%S}")
    add("")
    add("global-options:")
    add(f"    nsamps: {nsamps}")
    add(f"    scenario: {scenario}")
    add(f"    pyear_start: {pstart}")
    add(f"    pyear_end: {pend}")
    add(f"    pyear_step: {pstep}")
    add(f"    baseyear: {baseyear}")
    add(f'    pipeline_file: "{"pipeline.yml" if local else "pipeline.global.yml"}"')
    add("")
    add("climate_step:")
    add("    temperature:")
    add('        module_set: "fair"')
    add('        module: "temperature"')
    add("        generates_climate_output: true")
    add("")
    add("sealevel_step:")
    for key, module_set, module, module_wfs, options, flag in MODULES:
        if flag == "vlm" and (not use_vlm or not local):
            continue
        kept = [wf for wf in module_wfs if wf in workflows]
        if not kept:
            continue
        add(f"    {key}:")
        add(f'        module_set: "{module_set}"')
        add(f'        module: "{module}"')
        if flag == "ais":
            add(f'        pipeline_file: "{"pipeline.AIS.yml" if local else "pipeline.AIS.global.yml"}"')
        chosen_options = options
        if flag == "lws":
            chosen_options = (("scenario", f'"{lws_scenario}"'), ("dcrate_lo", "-0.4"))
        if chosen_options:
            add("        options:")
            for name, value in chosen_options:
                add(f"            {name}: {value}")
        add("        include_in_workflow:")
        for wf in kept:
            add(f'            - "{wf}"')
        add("")
    add("totaling_step:")
    add("    total:")
    add('        module_set: "facts"')
    add('        module: "total"')
    add("        loop_over_workflows: true")
    add("        loop_over_scales: true")
    add("        stages:")
    add("            - workflow")
    if use_esl and local:
        add("")
        add("esl_step:")
        add("    extremesealevel:")
        add("        loop_over_workflows: true")
        add('        module_set: "extremesealevel"')
        add('        module: "pointsoverthreshold"')
        add("        options:")
        add(f"            target_years: {esl_years or '2050,2100'}")
        add('            total_localsl_file: "$SHARED/totaled/%EXPERIMENT_NAME%.total.workflow.%WORKFLOW_NAME%.local.nc"')
    return "\n".join(lines) + "\n"


class TaskWorker(QThread):
    output = Signal(str)
    completed = Signal(int, str)

    def __init__(self, task: Callable[[Callable[[str], None], Callable[[], bool]], None]):
        super().__init__()
        self.task = task
        self.process: subprocess.Popen[str] | None = None

    def stream(self, command: list[str], cwd: Path | None = None) -> int:
        self.output.emit("$ " + subprocess.list2cmdline(command) + "\n")
        self.process = subprocess.Popen(
            command, cwd=str(cwd) if cwd else None, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, text=True, encoding="utf-8", errors="replace",
            bufsize=1)
        assert self.process.stdout is not None
        for line in self.process.stdout:
            self.output.emit(line)
            if self.isInterruptionRequested():
                self.process.terminate()
                break
        return self.process.wait()

    def run(self) -> None:
        try:
            self.task(self.output.emit, self.isInterruptionRequested)
            self.completed.emit(0, "Completed successfully")
        except Exception as exc:  # GUI boundary: show actionable error
            self.output.emit("\nERROR: " + str(exc) + "\n")
            self.completed.emit(1, str(exc))

    def cancel(self) -> None:
        self.requestInterruption()
        if self.process is not None and self.process.poll() is None:
            self.process.terminate()


class LocationMap(QWebEngineView):
    """Interactive Esri basemap with FACTS station overlays."""

    def __init__(self) -> None:
        super().__init__()
        self.setMinimumHeight(290)

    def set_locations(self, points: list[tuple[str, str, float, float]], local: bool) -> None:
        records = [dict(name=name, station=station, lat=lat, lon=lon)
                   for name, station, lat, lon in points]
        data = json.dumps(records, ensure_ascii=True).replace("</", "<\\/")
        view_script = "group.getBounds().pad(0.12)" if local else "[[ -80, -175 ], [ 80, 175 ]]"
        max_zoom = "8" if local else "3"
        empty_view = "[20, -30], 2" if not local else "[38, -75], 4"
        mode = ("Local projection: selected stations are used"
                if local else "Global mean projection: stations are preview only")
        marker_radius = 6 if local else 8
        page = f"""<!doctype html>
<html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<style>
html,body,#map{{height:100%;margin:0;background:#e7eef2;font-family:Segoe UI,Arial,sans-serif}}
.scope{{position:absolute;z-index:500;top:10px;right:10px;background:rgba(255,255,255,.94);
padding:6px 9px;border-radius:4px;color:#18313d;font-size:12px;box-shadow:0 1px 4px #5577}}
</style></head><body><div id="map"></div><div class="scope">{mode} • {len(records)} station(s)</div>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
const points={data};
const map=L.map('map',{{zoomControl:true,attributionControl:true}});
L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{{z}}/{{y}}/{{x}}',{{
  maxZoom:19,
  attribution:'Tiles &copy; Esri, Sources: Esri, HERE, Garmin, USGS, NOAA and contributors'
}}).addTo(map);
const group=L.featureGroup().addTo(map);
points.forEach(p=>{{
  const marker=L.circleMarker([p.lat,p.lon],{{radius:{marker_radius},color:'#ffffff',weight:1.5,
    fillColor:'#c83f36',fillOpacity:.95}}).addTo(group);
  const detail=document.createElement('div');
  const strong=document.createElement('strong'); strong.textContent=p.name;
  const rest=document.createElement('div');
  rest.textContent='Station '+p.station+' · '+p.lat.toFixed(4)+', '+p.lon.toFixed(4);
  detail.append(strong,rest); marker.bindPopup(detail); marker.bindTooltip(p.name);
}});
if(points.length) map.fitBounds({view_script},{{padding:[20,20],maxZoom:{max_zoom}}});
else map.setView({empty_view});
</script></body></html>"""
        self.setHtml(page, QUrl("https://server.arcgisonline.com/"))


class FactsWindow(QMainWindow):
    def __init__(self) -> None:
        super().__init__()
        self.root = package_root()
        self.settings = QSettings("FACTS", "ProjectionStudio")
        self.worker: TaskWorker | None = None
        self.selected_station_ids: set[str] | None = None
        self.setWindowTitle("FACTS Projection Studio")
        self.resize(1280, 860)
        self.setMinimumSize(1040, 700)
        self._build_ui()
        self._apply_style()
        self.status.setText("Application ready: checking FACTS components…")
        # Let the native window appear before Docker/WSL checks begin.
        QTimer.singleShot(100, self.check_system)

    def _build_ui(self) -> None:
        central = QWidget()
        page = QVBoxLayout(central)
        page.setContentsMargins(24, 20, 24, 18)
        page.setSpacing(12)

        title = QLabel("FACTS Projection Studio")
        title.setObjectName("title")
        subtitle = QLabel("Install, configure, and run probabilistic global or local sea-level projections.")
        subtitle.setObjectName("subtitle")
        page.addWidget(title)
        page.addWidget(subtitle)

        self.tabs = QTabWidget()
        self.tabs.addTab(self._setup_tab(), "FACTS Setup")
        self.tabs.addTab(self._run_tab(), "Run projections")
        self.tabs.addTab(self._about_tab(), "About")
        page.addWidget(self.tabs, 1)

        self.status = QLabel("Ready")
        self.status.setObjectName("status")
        page.addWidget(self.status)
        self.setCentralWidget(central)

    def _setup_tab(self) -> QWidget:
        tab = QWidget()
        layout = QVBoxLayout(tab)
        layout.setContentsMargins(16, 16, 16, 16)
        layout.setSpacing(12)

        intro = QLabel(
            "Open this tab first. Check the computer, then install or repair only the missing FACTS components. "
            "Docker Desktop must be installed and running.")
        intro.setWordWrap(True)
        layout.addWidget(intro)

        self.checks = QTableWidget(7, 3)
        self.checks.setHorizontalHeaderLabels(("Component", "Status", "Details"))
        self.checks.verticalHeader().setVisible(False)
        self.checks.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.checks.setSelectionMode(QTableWidget.SelectionMode.NoSelection)
        self.checks.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.checks.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.ResizeToContents)
        self.checks.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Stretch)
        layout.addWidget(self.checks)

        options = QHBoxLayout()
        self.full_data = QCheckBox("Download full local module data (large and resumable; allow about 60 GB)")
        self.rebuild = QCheckBox("Rebuild existing Docker images")
        options.addWidget(self.full_data)
        options.addWidget(self.rebuild)
        options.addStretch(1)
        layout.addLayout(options)

        actions = QHBoxLayout()
        self.check_button = QPushButton("Check system")
        self.check_button.clicked.connect(self.check_system)
        self.install_button = QPushButton("Install / repair FACTS")
        self.install_button.setObjectName("primary")
        self.install_button.clicked.connect(self.install_facts)
        self.cancel_setup = QPushButton("Cancel")
        self.cancel_setup.setEnabled(False)
        self.cancel_setup.clicked.connect(self.cancel_task)
        actions.addWidget(self.check_button)
        actions.addStretch(1)
        actions.addWidget(self.cancel_setup)
        actions.addWidget(self.install_button)
        layout.addLayout(actions)

        self.setup_log = QTextEdit()
        self.setup_log.setReadOnly(True)
        self.setup_log.setFont(QFont("Cascadia Mono", 9))
        self.setup_log.setPlaceholderText("Installation and status output will appear here.")
        layout.addWidget(self.setup_log, 1)
        return tab

    def _run_tab(self) -> QWidget:
        tab = QWidget()
        outer = QVBoxLayout(tab)
        outer.setContentsMargins(16, 16, 16, 16)
        splitter = QSplitter(Qt.Orientation.Horizontal)

        left_scroll = QScrollArea()
        left_scroll.setWidgetResizable(True)
        left = QWidget()
        form = QVBoxLayout(left)
        form.setContentsMargins(2, 2, 10, 2)

        project = QGroupBox("Projection configuration")
        grid = QGridLayout(project)
        self.scenario = QComboBox(); self.scenario.addItems(SCENARIOS); self.scenario.setCurrentText("ssp126")
        self.scale = QComboBox(); self.scale.addItems((
            "Local relative sea level (uses location list)",
            "Global mean sea level (no locations required)",
        ))
        self.nsamps = QSpinBox(); self.nsamps.setRange(10, 100000); self.nsamps.setValue(2000)
        self.baseyear = QSpinBox(); self.baseyear.setRange(1800, 2200); self.baseyear.setValue(2005)
        self.pstart = QSpinBox(); self.pstart.setRange(2000, 2200); self.pstart.setValue(2020)
        self.pend = QSpinBox(); self.pend.setRange(2020, 2300); self.pend.setValue(2150)
        self.pstep = QSpinBox(); self.pstep.setRange(1, 50); self.pstep.setValue(10)
        fields = (("Scenario", self.scenario), ("Output scale", self.scale),
                  ("Monte Carlo samples", self.nsamps), ("Base year", self.baseyear),
                  ("Projection start", self.pstart), ("Projection end", self.pend),
                  ("Year step", self.pstep))
        for row, (label, widget) in enumerate(fields):
            grid.addWidget(QLabel(label), row, 0); grid.addWidget(widget, row, 1)
        form.addWidget(project)

        paths = QGroupBox("Input and output")
        path_grid = QGridLayout(paths)
        default_locations = self.root / "configs" / "location_48gauges.lst"
        self.locations = QLineEdit(str(default_locations))
        loc_browse = QPushButton("Browse…"); loc_browse.clicked.connect(self.choose_locations)
        self.select_locations_button = QPushButton("Choose stations…")
        self.select_locations_button.setObjectName("locationAction")
        self.select_locations_button.clicked.connect(self.select_locations)
        use_all_locations = QPushButton("Use all stations")
        use_all_locations.clicked.connect(self.use_all_locations)
        one_location = QPushButton("One-station test")
        one_location.clicked.connect(self.use_one_location)
        default_output = Path(self.settings.value(
            "output", str(Path.home() / "Documents" / "FACTS Outputs")))
        self.output_dir = QLineEdit(str(default_output))
        out_browse = QPushButton("Browse…"); out_browse.clicked.connect(self.choose_output)
        self.location_count = QLabel("")
        path_grid.addWidget(QLabel("Location list"), 0, 0)
        path_grid.addWidget(self.locations, 0, 1); path_grid.addWidget(loc_browse, 0, 2)
        path_grid.addWidget(QLabel("Stations to run"), 1, 0)
        path_grid.addWidget(self.location_count, 1, 1)
        path_grid.addWidget(self.select_locations_button, 1, 2)
        quick_locations = QHBoxLayout()
        quick_locations.addWidget(use_all_locations)
        quick_locations.addWidget(one_location)
        quick_locations.addStretch(1)
        path_grid.addLayout(quick_locations, 2, 1, 1, 2)
        path_grid.addWidget(QLabel("Output directory"), 3, 0)
        path_grid.addWidget(self.output_dir, 3, 1); path_grid.addWidget(out_browse, 3, 2)
        form.addWidget(paths)

        workflows = QGroupBox("FACTS workflows: blue means selected")
        wf_grid = QGridLayout(workflows)
        self.workflow_checks: dict[str, QPushButton] = {}
        descriptions = {
            "wf1e": "Emulated ice sheets", "wf1f": "AR5/FittedISMIP",
            "wf2e": "LARMIP + emulation", "wf2f": "LARMIP + fitted",
            "wf3e": "DeConto21 + emulation", "wf3f": "DeConto21 + fitted",
            "wf4": "Bamber19 structured expert judgement",
        }
        for index, wf in enumerate(WORKFLOWS):
            check = QPushButton(f"{wf}: {descriptions[wf]}")
            check.setObjectName("choice")
            check.setCheckable(True)
            check.setChecked(True)
            self.workflow_checks[wf] = check
            wf_grid.addWidget(check, index // 2, index % 2)
            check.toggled.connect(self.update_workflow_count)
        wf_actions = QHBoxLayout()
        select_all = QPushButton("Select all")
        select_all.clicked.connect(lambda: self.set_all_workflows(True))
        clear_all = QPushButton("Clear all")
        clear_all.clicked.connect(lambda: self.set_all_workflows(False))
        self.workflow_count = QLabel("")
        wf_actions.addWidget(select_all)
        wf_actions.addWidget(clear_all)
        wf_actions.addStretch(1)
        wf_actions.addWidget(self.workflow_count)
        wf_grid.addLayout(wf_actions, 4, 0, 1, 2)
        self.update_workflow_count()
        form.addWidget(workflows)

        optional = QGroupBox("Optional modules and resources: blue means selected")
        opt = QFormLayout(optional)
        self.vlm = QPushButton("Vertical land motion (required for relative sea level)")
        self.vlm.setObjectName("choice")
        self.vlm.setCheckable(True)
        self.vlm.setChecked(True)
        self.esl = QPushButton("Extreme sea level: points over threshold")
        self.esl.setObjectName("choice")
        self.esl.setCheckable(True)
        self.esl.setChecked(False)
        self.esl_years = QLineEdit("2050,2100")
        self.esl_years.setEnabled(False)
        self.esl.toggled.connect(self.esl_years.setEnabled)
        self.cpu = QSpinBox(); self.cpu.setRange(1, 128); self.cpu.setValue(8)
        self.memory = QLineEdit("12g")
        opt.addRow(self.vlm); opt.addRow(self.esl); opt.addRow("ESL target years", self.esl_years)
        opt.addRow("Container CPUs", self.cpu); opt.addRow("Memory limit", self.memory)
        form.addWidget(optional)
        form.addStretch(1)
        left_scroll.setWidget(left)

        right = QWidget()
        right_layout = QVBoxLayout(right)
        right_layout.setContentsMargins(10, 2, 2, 2)
        vertical_splitter = QSplitter(Qt.Orientation.Vertical)

        map_panel = QWidget()
        map_layout = QVBoxLayout(map_panel)
        map_layout.setContentsMargins(0, 0, 0, 0)
        map_title = QLabel("Location map"); map_title.setObjectName("panelTitle")
        map_layout.addWidget(map_title)
        self.location_map = LocationMap()
        map_layout.addWidget(self.location_map, 1)

        console_panel = QWidget()
        console_layout = QVBoxLayout(console_panel)
        console_layout.setContentsMargins(0, 0, 0, 0)
        log_title = QLabel("Execution console"); log_title.setObjectName("panelTitle")
        console_layout.addWidget(log_title)
        self.run_log = QTextEdit(); self.run_log.setReadOnly(True)
        self.run_log.setFont(QFont("Cascadia Mono", 9))
        self.run_log.setPlaceholderText("FACTS task output and progress will appear here.")
        console_layout.addWidget(self.run_log, 1)
        self.progress = QProgressBar(); self.progress.setRange(0, 100); self.progress.setValue(0)
        console_layout.addWidget(self.progress)
        run_actions = QHBoxLayout()
        preview = QPushButton("Preview configuration"); preview.clicked.connect(self.preview_config)
        self.cancel_run = QPushButton("Stop run"); self.cancel_run.setEnabled(False); self.cancel_run.clicked.connect(self.cancel_task)
        self.generate_button = QPushButton("Generate HTML dashboard")
        self.generate_button.clicked.connect(self.generate_dashboard)
        self.open_html_button = QPushButton("Open latest HTML")
        self.open_html_button.clicked.connect(self.open_latest_dashboard)
        self.run_button = QPushButton("Run projection"); self.run_button.setObjectName("primary"); self.run_button.clicked.connect(self.run_projection)
        run_actions.addWidget(preview)
        run_actions.addWidget(self.generate_button)
        run_actions.addWidget(self.open_html_button)
        run_actions.addStretch(1)
        run_actions.addWidget(self.cancel_run); run_actions.addWidget(self.run_button)
        console_layout.addLayout(run_actions)

        vertical_splitter.addWidget(map_panel)
        vertical_splitter.addWidget(console_panel)
        vertical_splitter.setSizes((330, 390))
        vertical_splitter.setCollapsible(0, False)
        vertical_splitter.setCollapsible(1, False)
        right_layout.addWidget(vertical_splitter, 1)

        splitter.addWidget(left_scroll); splitter.addWidget(right)
        splitter.setSizes((470, 730))
        outer.addWidget(splitter)
        self.locations.textChanged.connect(self.location_source_changed)
        self.scale.currentIndexChanged.connect(self.update_location_count)
        self.update_location_count()
        return tab

    def _about_tab(self) -> QWidget:
        tab = QWidget()
        layout = QVBoxLayout(tab)
        layout.setContentsMargins(28, 28, 28, 28)
        layout.setSpacing(16)

        heading = QLabel("About FACTS Projection Studio")
        heading.setObjectName("title")
        layout.addWidget(heading)

        description = QLabel(
            "A desktop interface for installing, configuring, running, and reviewing "
            "projections from the Framework for Assessing Changes To Sea-level (FACTS).")
        description.setObjectName("aboutLead")
        description.setWordWrap(True)
        layout.addWidget(description)

        developer_card = QGroupBox("Dashboard developer")
        developer_card.setObjectName("aboutCard")
        developer_layout = QVBoxLayout(developer_card)
        developer = QLabel(
            "Faezeh Maghsoodifar\nThe University of Alabama")
        developer.setObjectName("panelTitle")
        developer.setWordWrap(True)
        developer_layout.addWidget(developer)
        layout.addWidget(developer_card)

        citation_card = QGroupBox("FACTS 2023 paper")
        citation_card.setObjectName("aboutCard")
        citation_layout = QVBoxLayout(citation_card)
        citation = QLabel(
            "Kopp, R. E., Garner, G. G., Hermans, T. H. J., Jha, S., Kumar, P., "
            "Reedy, A., Slangen, A. B. A., Turilli, M., Edwards, T. L., Gregory, "
            "J. M., Koubbe, G., Levermann, A., Merzky, A., Nowicki, S., Palmer, "
            "M. D., & Smith, C. (2023). The Framework for Assessing Changes To "
            "Sea-level (FACTS) v1.0: A platform for characterizing parametric and "
            "structural uncertainty in future global, relative, and extreme "
            "sea-level change. <i>Geoscientific Model Development, 16</i>, "
            "7461–7489. <a style=\"color: #c62828;\" "
            "href=\"https://doi.org/10.5194/gmd-16-7461-2023\">"
            "https://doi.org/10.5194/gmd-16-7461-2023</a>")
        citation.setWordWrap(True)
        citation.setOpenExternalLinks(True)
        citation.setTextInteractionFlags(Qt.TextInteractionFlag.TextBrowserInteraction)
        citation_layout.addWidget(citation)
        layout.addWidget(citation_card)

        disclaimer_card = QGroupBox("Independent-use disclaimer")
        disclaimer_card.setObjectName("disclaimerCard")
        disclaimer_layout = QVBoxLayout(disclaimer_card)
        note = QLabel(
            "This dashboard was independently developed by a FACTS user "
            "to make practical use of FACTS easier. It is not affiliated with, "
            "endorsed by, or maintained by the FACTS development team. FACTS remains "
            "an independent open-source scientific framework.")
        note.setWordWrap(True)
        disclaimer_layout.addWidget(note)
        layout.addWidget(disclaimer_card)
        layout.addStretch(1)
        return tab

    def _apply_style(self) -> None:
        self.setStyleSheet("""
            QMainWindow, QWidget { background: #f3f6f8; color: #16252d; }
            QLabel { background: transparent; }
            QLabel#title { color: #0b2b3c; font-size: 28px; font-weight: 700; }
            QLabel#subtitle { color: #60717a; font-size: 14px; }
            QLabel#panelTitle { color: #0b2b3c; font-size: 16px; font-weight: 700; }
            QLabel#status { background: #ffffff; border: 1px solid #d9e2e7; padding: 8px 12px; }
            QTabWidget::pane { background: #ffffff; border: 1px solid #d9e2e7; }
            QTabBar::tab { background: #dfe8ec; color: #52656f; padding: 11px 22px; font-weight: 650; border-top-left-radius: 6px; border-top-right-radius: 6px; margin-right: 3px; }
            QTabBar::tab:hover { background: #cedde3; color: #173b4c; }
            QTabBar::tab:selected { background: #1976d2; color: #ffffff; }
            QGroupBox { background: #ffffff; border: 1px solid #d9e2e7; border-radius: 6px; margin-top: 12px; padding: 14px 10px 10px; font-weight: 650; color: #0b2b3c; }
            QGroupBox::title { subcontrol-origin: margin; left: 12px; padding: 0 5px; }
            QLabel#aboutLead { color: #47626f; font-size: 15px; padding: 2px 0 8px 0; }
            QGroupBox#aboutCard { border: 1px solid #cbdfe8; border-left: 5px solid #1976d2; border-radius: 8px; padding: 18px 16px 14px 16px; }
            QGroupBox#aboutCard::title { color: #145ea8; font-size: 15px; font-weight: 700; left: 16px; }
            QGroupBox#disclaimerCard { background: #fff8e8; border: 1px solid #efd496; border-left: 5px solid #d99a16; border-radius: 8px; padding: 18px 16px 14px 16px; }
            QGroupBox#disclaimerCard::title { color: #805600; font-size: 15px; font-weight: 700; left: 16px; }
            QLineEdit, QComboBox, QSpinBox, QTableWidget { background: #ffffff; border: 1px solid #cbd8de; border-radius: 3px; padding: 6px; }
            QTextEdit { background: #0c2029; color: #dce9ed; border: 0; border-radius: 4px; padding: 8px; }
            QPushButton { background: #e6eef1; border: 0; border-radius: 4px; padding: 8px 14px; font-weight: 600; }
            QPushButton:hover { background: #d8e5e9; }
            QPushButton:disabled { color: #97a5ab; background: #edf1f3; }
            QPushButton#choice { background: #e6eef1; color: #16252d; text-align: left; border: 1px solid #d3dfe4; }
            QPushButton#choice:hover { background: #d8e5e9; }
            QPushButton#choice:checked { background: #1976d2; color: #ffffff; border-color: #1565c0; }
            QPushButton#choice:checked:hover { background: #1565c0; }
            QPushButton#locationAction { background: #1976d2; color: #ffffff; }
            QPushButton#locationAction:hover { background: #1565c0; }
            QTableWidget#locationSelector::item:selected { background: #1976d2; color: #ffffff; }
            QPushButton#primary { color: white; background: #087f73; padding: 9px 18px; }
            QPushButton#primary:hover { background: #066a61; }
            QProgressBar { background: #dce7ea; border: 0; border-radius: 4px; height: 10px; text-align: center; }
            QProgressBar::chunk { background: #087f73; border-radius: 4px; }
            QScrollArea { border: 0; background: #ffffff; }
        """)

    def set_busy(self, busy: bool, message: str) -> None:
        self.status.setText(message)
        for button in (self.check_button, self.install_button, self.run_button,
                       self.generate_button):
            button.setEnabled(not busy)
        self.cancel_setup.setEnabled(busy)
        self.cancel_run.setEnabled(busy)

    def append_setup(self, text: str) -> None:
        self.setup_log.moveCursor(self.setup_log.textCursor().MoveOperation.End)
        self.setup_log.insertPlainText(text)
        self.setup_log.ensureCursorVisible()

    def append_run(self, text: str) -> None:
        self.run_log.moveCursor(self.run_log.textCursor().MoveOperation.End)
        self.run_log.insertPlainText(text)
        match = re.search(r"tasks\s+(\d+)/(\d+)", text)
        if match:
            done, total = map(int, match.groups())
            self.progress.setValue(min(99, round(done * 100 / max(total, 1))))
        self.run_log.ensureCursorVisible()

    def start_task(self, task: Callable, output: Callable[[str], None], label: str) -> None:
        if self.worker is not None and self.worker.isRunning():
            QMessageBox.information(self, "FACTS is busy", "Wait for the active operation to finish.")
            return
        self.set_busy(True, label)
        self.worker = TaskWorker(task)
        self.worker.output.connect(output)
        self.worker.completed.connect(self.task_finished)
        self.worker.start()

    def task_finished(self, code: int, message: str) -> None:
        self.set_busy(False, message if code == 0 else "Failed: " + message)
        if code == 0:
            self.progress.setValue(100 if self.tabs.currentIndex() == 1 else self.progress.value())
        self.worker = None
        self.check_system()

    def cancel_task(self) -> None:
        if self.worker is not None:
            self.worker.cancel()
            self.status.setText("Cancelling…")

    def status_rows(self) -> list[tuple[str, bool, str]]:
        docker_ok, docker_detail = docker_ready()
        ubuntu_ok = ubuntu_available()
        tools_ok = False
        home = ""
        if ubuntu_ok:
            code, detail = run_capture(["wsl.exe", "-d", "Ubuntu", "--", "bash", "-lc",
                                        "command -v python3 && python3 -c 'import tkinter' && command -v git && command -v wget"], 30)
            tools_ok = code == 0
            try: home = wsl_home()
            except RuntimeError: pass
        repo = f"{home}/facts_ssisls/facts" if home else "~/facts_ssisls/facts"
        repo_ok = ubuntu_ok and run_capture(
            ["wsl.exe", "-d", "Ubuntu", "--", "test", "-d", repo + "/.git"], 15)[0] == 0
        image_ok = docker_ok and run_capture(["docker.exe", "image", "inspect", "ssisls"], 20)[0] == 0
        viz_ok = docker_ok and run_capture(["docker.exe", "image", "inspect", "facts-viz"], 20)[0] == 0
        script_ok = (self.root / "setup_facts.sh").is_file() and (self.root / "run_facts_slr.sh").is_file()
        return [
            ("Windows application", True, "Native bundled interface"),
            ("Docker Desktop", docker_ok, docker_detail),
            ("Ubuntu WSL2", ubuntu_ok, "Installed" if ubuntu_ok else "Installed from this tab"),
            ("Ubuntu tools", tools_ok, "Python/Tk/Git/wget"),
            ("FACTS repository", repo_ok, repo),
            ("FACTS Docker image", image_ok, "ssisls"),
            ("Dashboard image", viz_ok and script_ok, "facts-viz and package launchers"),
        ]

    def check_system(self) -> None:
        rows = self.status_rows()
        for row, (name, ready, detail) in enumerate(rows):
            for column, value in enumerate((name, "Ready" if ready else "Missing", detail)):
                item = QTableWidgetItem(str(value))
                item.setForeground(Qt.GlobalColor.darkGreen if ready else Qt.GlobalColor.darkRed)
                self.checks.setItem(row, column, item)
        ready_count = sum(ready for _name, ready, _detail in rows)
        self.status.setText(f"System check: {ready_count}/{len(rows)} components ready")

    def install_facts(self) -> None:
        include_full_data = self.full_data.isChecked()
        rebuild_images = self.rebuild.isChecked()
        if QMessageBox.question(
            self, "Install or repair FACTS",
            "Install missing WSL/Ubuntu tools, FACTS repositories, data, and Docker images?\n\n"
            + ("Full local module data is selected (large resumable download, about 60 GB)."
               if include_full_data else "Full local module data is not selected."),
        ) != QMessageBox.StandardButton.Yes:
            return
        self.setup_log.clear()

        def task(log: Callable[[str], None], cancelled: Callable[[], bool]) -> None:
            docker_ok, detail = docker_ready()
            if not docker_ok:
                raise RuntimeError("Start Docker Desktop, then select Install again. " + detail)
            if not ubuntu_available():
                log("Installing Ubuntu WSL2. Accept the Windows administrator prompt.\n")
                ps = "$p=Start-Process -FilePath wsl.exe -ArgumentList @('--install','--distribution','Ubuntu','--no-launch') -Verb RunAs -Wait -PassThru; exit $p.ExitCode"
                code = subprocess.call(["powershell.exe", "-NoLogo", "-NoProfile", "-Command", ps])
                if code != 0 or not ubuntu_available():
                    raise RuntimeError("Ubuntu installation needs a Windows restart. Restart, then reopen this application.")
            log("Installing Ubuntu-side prerequisites…\n")
            apt = "export DEBIAN_FRONTEND=noninteractive; apt-get update && apt-get install -y python3 python3-tk git wget curl ca-certificates"
            worker = self.worker
            if worker is None or worker.stream(
                ["wsl.exe", "-d", "Ubuntu", "-u", "root", "--", "bash", "-lc", apt]) != 0:
                raise RuntimeError("Ubuntu prerequisite installation failed.")
            args = ["wsl.exe", "-d", "Ubuntu", "--cd", str(self.root), "--",
                    "bash", "setup_facts.sh"]
            if include_full_data: args.append("--with-data")
            if rebuild_images: args.append("--rebuild")
            if worker is None or worker.stream(args, self.root) != 0:
                raise RuntimeError("FACTS setup failed. Review the Setup console above.")

        self.start_task(task, self.append_setup, "Installing FACTS…")

    def choose_locations(self) -> None:
        selected, _ = QFileDialog.getOpenFileName(
            self, "Choose FACTS location list", str(self.root / "configs"),
            "Location lists (*.lst *.txt *.tsv);;All files (*)")
        if selected: self.locations.setText(selected)

    def location_source_changed(self) -> None:
        self.selected_station_ids = None
        self.update_location_count()

    def choose_output(self) -> None:
        selected = QFileDialog.getExistingDirectory(
            self, "Choose output directory", self.output_dir.text())
        if selected:
            self.output_dir.setText(selected)
            self.settings.setValue("output", selected)

    def all_location_rows(self) -> list[str]:
        path = Path(self.locations.text().strip())
        if not path.is_file(): return []
        rows = []
        for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw.strip()
            if not line or line.startswith("#"): continue
            parts = line.split("\t")
            if len(parts) != 4: continue
            try: int(parts[1]); float(parts[2]); float(parts[3])
            except ValueError: continue
            rows.append("\t".join(parts))
        return rows

    def valid_location_rows(self) -> list[str]:
        rows = self.all_location_rows()
        if self.selected_station_ids is None:
            return rows
        return [row for row in rows if row.split("\t")[1] in self.selected_station_ids]

    def select_locations(self) -> None:
        rows = self.all_location_rows()
        if not rows:
            QMessageBox.warning(self, "No valid locations", "Choose a valid location-list file first.")
            return
        selected_ids = (self.selected_station_ids if self.selected_station_ids is not None
                        else {row.split("\t")[1] for row in rows})
        dialog = QDialog(self)
        dialog.setWindowTitle("Select FACTS locations")
        dialog.resize(760, 620)
        layout = QVBoxLayout(dialog)
        instructions = QLabel(
            "Click any row to select or unselect it. Blue rows will be included in the FACTS run.")
        instructions.setWordWrap(True)
        layout.addWidget(instructions)
        table = QTableWidget(len(rows), 4)
        table.setObjectName("locationSelector")
        table.setHorizontalHeaderLabels(("Location", "Station ID", "Latitude", "Longitude"))
        table.verticalHeader().setVisible(False)
        table.setSelectionBehavior(QTableWidget.SelectionBehavior.SelectRows)
        table.setSelectionMode(QTableWidget.SelectionMode.MultiSelection)
        table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
        for index, row in enumerate(rows):
            name, station, latitude, longitude = row.split("\t")
            name_item = QTableWidgetItem(name.replace("_", " "))
            table.setItem(index, 0, name_item)
            table.setItem(index, 1, QTableWidgetItem(station))
            table.setItem(index, 2, QTableWidgetItem(latitude))
            table.setItem(index, 3, QTableWidgetItem(longitude))
            if station in selected_ids:
                table.selectionModel().select(
                    table.model().index(index, 0),
                    QItemSelectionModel.SelectionFlag.Select
                    | QItemSelectionModel.SelectionFlag.Rows)
        layout.addWidget(table)
        actions = QHBoxLayout()
        select_all = QPushButton("Select all")
        select_all.clicked.connect(table.selectAll)
        clear_all = QPushButton("Clear all")
        clear_all.clicked.connect(table.clearSelection)
        actions.addWidget(select_all); actions.addWidget(clear_all); actions.addStretch(1)
        layout.addLayout(actions)
        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Cancel | QDialogButtonBox.StandardButton.Ok)
        buttons.accepted.connect(dialog.accept); buttons.rejected.connect(dialog.reject)
        layout.addWidget(buttons)
        if dialog.exec() != QDialog.DialogCode.Accepted:
            return
        self.selected_station_ids = {
            table.item(index.row(), 1).text()
            for index in table.selectionModel().selectedRows(0)
        }
        self.update_location_count()

    def use_all_locations(self) -> None:
        if not self.all_location_rows():
            QMessageBox.warning(self, "No valid locations", "Choose a valid location-list file first.")
            return
        self.selected_station_ids = None
        self.update_location_count()

    def use_one_location(self) -> None:
        rows = self.all_location_rows()
        if not rows:
            QMessageBox.warning(self, "No valid locations", "Choose a valid location-list file first.")
            return
        self.selected_station_ids = {rows[0].split("\t")[1]}
        self.update_location_count()

    def location_points(self) -> list[tuple[str, str, float, float]]:
        points = []
        for row in self.valid_location_rows():
            name, station, latitude, longitude = row.split("\t")
            points.append((name.replace("_", " "), station, float(latitude), float(longitude)))
        return points

    def update_location_count(self) -> None:
        points = self.location_points()
        count = len(points)
        total = len(self.all_location_rows())
        suffix = (": used by local projection" if self.scale.currentIndex() == 0
                  else ": map preview only; global mean has no station points")
        self.location_count.setText(
            f"{count} of {total} valid locations selected{suffix}")
        if hasattr(self, "location_map"):
            self.location_map.set_locations(points, self.scale.currentIndex() == 0)

    def selected_workflows(self) -> list[str]:
        return [wf for wf, check in self.workflow_checks.items() if check.isChecked()]

    def set_all_workflows(self, selected: bool) -> None:
        for check in self.workflow_checks.values():
            check.setChecked(selected)

    def update_workflow_count(self) -> None:
        selected = len(self.selected_workflows())
        self.workflow_count.setText(f"{selected} of {len(WORKFLOWS)} selected")

    def current_config(self) -> str:
        return build_config(
            self.scenario.currentText(), self.scale.currentIndex() == 0,
            self.selected_workflows(), self.vlm.isChecked(), self.esl.isChecked(),
            self.esl_years.text().strip(), self.nsamps.value(), self.baseyear.value(),
            self.pstart.value(), self.pend.value(), self.pstep.value())

    def preview_config(self) -> None:
        dialog = QMessageBox(self)
        dialog.setWindowTitle("Generated FACTS configuration")
        dialog.setText("The configuration below will be installed when the run starts.")
        dialog.setDetailedText(self.current_config())
        dialog.exec()

    def run_projection(self) -> None:
        rows = self.valid_location_rows()
        workflows = self.selected_workflows()
        output = Path(self.output_dir.text().strip())
        if not workflows:
            QMessageBox.warning(self, "No workflows", "Select at least one FACTS workflow.")
            return
        if self.scale.currentIndex() == 0 and not rows:
            QMessageBox.warning(self, "No locations", "Choose a valid tab-separated location list.")
            return
        try: output.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            QMessageBox.warning(self, "Output directory", str(exc)); return
        scenario = self.scenario.currentText()
        local_run = self.scale.currentIndex() == 0
        run_stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_root = output / "FACTS_runs" / f"{scenario}_{run_stamp}"
        result_dir = run_root / scenario
        if QMessageBox.question(
            self, "Run FACTS",
            f"Scenario: {scenario}\nScale: {self.scale.currentText()}\n"
            f"Locations: {len(rows) if local_run else 'not used for global mean'}\n"
            f"Workflows: {', '.join(workflows)}\nSamples: {self.nsamps.value():,}\n"
            f"Output: {result_dir}\n\nStart the projection?",
        ) != QMessageBox.StandardButton.Yes:
            return
        self.settings.setValue("output", str(output))
        self.settings.setValue(f"latest_result_dir/{scenario}", str(result_dir))
        runtime = self.root / ".runtime" / scenario
        runtime.mkdir(parents=True, exist_ok=True)
        config_path = runtime / "config.yml"
        locations_path = runtime / "location.lst"
        config_path.write_text(self.current_config(), encoding="utf-8", newline="\n")
        if local_run:
            locations_path.write_text("\n".join(rows) + "\n", encoding="utf-8", newline="\n")
        self.run_log.clear(); self.progress.setValue(0)
        cpu_count = self.cpu.value()
        memory_limit = self.memory.text().strip()

        def task(log: Callable[[str], None], cancelled: Callable[[], bool]) -> None:
            if not ubuntu_available(): raise RuntimeError("Complete FACTS Setup first: Ubuntu is missing.")
            home = wsl_home(); repo = home + "/facts_ssisls/facts"
            exp = repo + "/experiments_ssisls/" + scenario
            config_wsl = wsl_path(config_path)
            run_root.mkdir(parents=True, exist_ok=True)
            output_wsl = wsl_path(run_root)
            prep = (f"test -d {shlex.quote(exp)} && "
                    f"cp {shlex.quote(config_wsl)} {shlex.quote(exp + '/config.yml')}")
            if local_run:
                locations_wsl = wsl_path(locations_path)
                prep += (f" && cp {shlex.quote(locations_wsl)} "
                         f"{shlex.quote(exp + '/location.lst')}")
            code, detail = run_capture(["wsl.exe", "-d", "Ubuntu", "--", "bash", "-lc", prep], 30)
            if code != 0: raise RuntimeError("Could not install the experiment files: " + detail)
            log("Selected workflows: " + ", ".join(workflows) + "\n")
            log("Isolated result folder: " + str(result_dir) + "\n")
            worker = self.worker
            command = ["wsl.exe", "-d", "Ubuntu", "--cd", str(self.root), "--", "env",
                       "FACTS_REPO=" + repo, "OUTPUT_ROOT=" + output_wsl,
                       "CPU_COUNT=" + str(cpu_count), "MEMORY_LIMIT=" + memory_limit,
                       "bash", "run_facts_slr.sh", scenario]
            if worker is None or worker.stream(command, self.root) != 0:
                raise RuntimeError("FACTS run failed. Review the execution console.")

        self.tabs.setCurrentIndex(1)
        self.start_task(task, self.append_run, "Running " + scenario + "…")

    def generate_dashboard(self) -> None:
        scenario = self.scenario.currentText()
        output_root = Path(self.output_dir.text().strip())
        saved_result = self.settings.value(f"latest_result_dir/{scenario}", "")
        scenario_dir = (Path(str(saved_result)) if saved_result
                        else output_root / scenario)
        netcdf_files = list(scenario_dir.glob("*.nc")) if scenario_dir.is_dir() else []
        if not netcdf_files:
            QMessageBox.warning(
                self, "No FACTS results",
                f"No NetCDF output files were found in:\n{scenario_dir}\n\n"
                "Complete a projection first or choose its output directory.")
            return
        html_path = scenario_dir / f"facts_dashboard_{scenario}.html"
        selected_location_path = self.root / ".runtime" / scenario / "location.lst"
        location_path = (selected_location_path if selected_location_path.is_file()
                         else Path(self.locations.text().strip()))
        if QMessageBox.question(
            self, "Generate results dashboard",
            f"Create a self-contained interactive HTML dashboard from "
            f"{len(netcdf_files)} NetCDF file(s)?\n\nOutput: {html_path}",
        ) != QMessageBox.StandardButton.Yes:
            return
        self.run_log.clear()
        self.settings.setValue("latest_dashboard", str(html_path))

        def task(log: Callable[[str], None], cancelled: Callable[[], bool]) -> None:
            if not ubuntu_available():
                raise RuntimeError("Complete FACTS Setup first: Ubuntu is missing.")
            home = wsl_home()
            dashboard_repo = home + "/facts_ssisls/facts.plotting.dashboard"
            scenario_wsl = wsl_path(scenario_dir)
            html_wsl = wsl_path(html_path)
            command = (f"cd {shlex.quote(dashboard_repo)} && "
                       f"bash docker/run.sh --ssp-dir {shlex.quote(scenario_wsl)} "
                       f"--output {shlex.quote(html_wsl)} "
                       f"--title {shlex.quote('FACTS ' + scenario + ' projections')}")
            if location_path.is_file():
                command += " --location-lst " + shlex.quote(wsl_path(location_path))
            worker = self.worker
            if worker is None or worker.stream(
                ["wsl.exe", "-d", "Ubuntu", "--", "bash", "-lc", command]) != 0:
                raise RuntimeError("HTML dashboard generation failed. Review the console.")
            log(f"\nDashboard created: {html_path}\n")

        self.start_task(task, self.append_run, "Generating HTML dashboard…")

    def open_latest_dashboard(self) -> None:
        value = self.settings.value("latest_dashboard", "")
        path = Path(str(value)) if value else Path(
            self.output_dir.text().strip()) / f"facts_dashboard_{self.scenario.currentText()}.html"
        if not path.is_file():
            QMessageBox.information(
                self, "Dashboard not found",
                "Generate the HTML dashboard first, or select the output directory containing it.")
            return
        os.startfile(path)

    def closeEvent(self, event) -> None:
        if self.worker is not None and self.worker.isRunning():
            if QMessageBox.question(self, "Quit", "An operation is running. Quit anyway?") != QMessageBox.StandardButton.Yes:
                event.ignore(); return
            self.worker.cancel()
        event.accept()


def main() -> int:
    app = QApplication(sys.argv)
    app.setApplicationName("FACTS Projection Studio")
    app.setOrganizationName("FACTS")
    window = FactsWindow()
    window.show()
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
